name: sage-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - compilers
  - make
  - m4
  - perl
  - python
  - tar
  - bc
  - pkg-config
  - arb
  - boost-cpp
  - brial
  - bzip2
  - cddlib
  - cliquer
  - cmake
  - curl
  - ecl
  - eclib
  - ecm
  - fflas-ffpack
  - libflint
  - flintqs
  - fplll
  - freetype
  - bdw-gc
  - gengetopt
  - gf2x
  - gfan
  - fortran-compiler
  - giac
  - givaro
  - glpk
  - gmp
  - gsl
  - iml
  - lcalc
  - libatomic_ops
  - libbraiding
  - libffi
  - libgd
  - libhomfly
  - xz
  - libpng
  - linbox
  - lrcalc
  - m4ri
  - m4rie
  - mpc
  - mpfi
  - mpfr
  - nauty
  - ncurses
  - ntl
  - openblas
  - blas=2.*=openblas
  - openssl
  - palp
  - pari
  - pari-elldata
  - pari-galdata
  - pari-galpol
  - pari-seadata
  - pari-galdata
  - pari-seadata-small
  - patch
  - pcre
  - pkg-config
  - planarity
  - ppl
  - primecount
  - primesieve
  - qhull
  - r
  - r-essentials
  - readline
  - rw
  - singular
  - sqlite
  - suitesparse
  - symmetrica
  - sympow
  - tachyon
  - tox
  - xz
  - zeromq
  - zlib
  - zn_poly
  - alabaster
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - bleach
  - certifi
  - cffi
  - sagemath-db-combinatorial-designs
  - sagemath-db-conway-polynomials
  - cvxopt
  - cycler
  - cypari2
  - cysignals
  - cython
  - python-dateutil
  - decorator
  - defusedxml
  - docutils
  - sagemath-db-elliptic-curves
  - entrypoints
  - fpylll
  - gap-defaults
  - gmpy2
  - sagemath-db-graphs
  - html5lib
  - imagesize
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jmol
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - python-lrcalc
  - markupsafe
  - mathjax
  - "matplotlib>=3.5.1"
  - maxima
  - memory-allocator
  - mistune
  - mpmath
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numpy
  - packaging
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgconfig
  - sagemath-db-polytopes
  - pplpy
  - primecountpy
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pybind11
  - pycparser
  - pygments
  - pyparsing
  - pyrsistent
  - pytz
  - pyzmq
  - requests
  - rpy2
  - sagetex
  - scipy
  - send2trash
  - setuptools
  - setuptools_scm
  - simplegeneric
  - six
  - snowballstemmer
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - sympy
  - terminado
  - testpath
  - three.js
  - tornado
  - traitlets
  - tzlocal
  - vcversioner
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - zipp
  # Packages needed for ./bootstrap
  - gettext
  - autoconf
  - automake
  - libtool
  # Additional dev tools
  - openssh
  - pycodestyle
  - pytest
