name: Build & Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - develop
    # Ignore pushes on tags to prevent two uploads of codecov reports
    tags-ignore: ['**']
  workflow_dispatch:
    # Allow to run manually
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'ubuntu-focal-standard'
      docker_tag:
        description: 'Docker tag'
        required: true
        default: 'dev'

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Merge CI fixes from sagemath/sage
        run: |
          .ci/merge-fixes.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Start container
        run: |
          docker run --name BUILD -dit \
            --mount type=bind,src=$(pwd),dst=$(pwd) \
            --workdir $(pwd) \
            ghcr.io/sagemath/sage/sage-${{ github.event.inputs.platform || 'ubuntu-focal-standard' }}-with-targets:${{ github.event.inputs.docker_tag || 'dev'}} /bin/sh

      - name: Update system packages
        id: prepare
        run: |
          export PATH="build/bin:$PATH"
          eval $(sage-print-system-package-command auto update)
          eval $(sage-print-system-package-command auto --spkg --yes --no-install-recommends install git)
        shell: sh .ci/docker-exec-script.sh BUILD . {0}

      - name: Add prebuilt tree as a worktree
        id: worktree
        run: |
          git config --global --add safe.directory $(pwd)
          .ci/retrofit-worktree.sh worktree-image /sage
        shell: sh .ci/docker-exec-script.sh BUILD . {0}

      - name: Incremental build
        id: incremental
        run: |
          # Now re-bootstrap and build. The build is incremental because we were careful with the timestamps.
          ./bootstrap
          MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2 make build
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Build modularized distributions
        if: (success() || failure()) && steps.worktree.outcome == 'success'
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          make V=0 tox
          make SAGE_CHECK=no pypi-wheels
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Clean (fallback to non-incremental)
        id: clean
        if: (success() || failure()) && steps.worktree.outcome == 'success' && steps.incremental.outcome != 'success'
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          ./bootstrap && make doc-clean doc-uninstall sagelib-clean && git clean -fx src/sage && ./config.status
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Build
        # This step is needed because building the modularized distributions installs some optional packages,
        # so the editable install of sagelib needs to build the corresponding optional extension modules.
        id: build
        if: (success() || failure()) && (steps.incremental.outcome == 'success' || steps.clean.outcome == 'success')
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          make build
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      # Testing

      - name: Test changed files (sage -t --new)
        if: (success() || failure()) && steps.build.outcome == 'success'
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          # We run tests with "sage -t --new"; this only tests the uncommitted changes.
          ./sage -t --new -p2
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Test modularized distributions
        if: (success() || failure()) && steps.build.outcome == 'success'
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          make V=0 tox && make pypi-wheels-check
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Pytest
        if: contains(github.ref, 'pytest')
        run: |
          ./sage -python -m pip install coverage pytest-xdist
          ./sage -python -m coverage run -m pytest -c tox.ini --doctest-modules || true
        # Increase the length of the lines in the "short summary"
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image COLUMNS=120 {0}

      - name: Test all files (sage -t --all --long)
        if: (success() || failure()) && steps.build.outcome == 'success'
        run: |
          ./sage -python -m pip install coverage
          ./sage -python -m coverage run ./bin/sage-runtests --all --long -p2 --random-seed=286735480429121101562228604801325644303
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Prepare coverage results
        if: (success() || failure()) && steps.build.outcome == 'success'
        run: |
          ./venv/bin/python3 -m coverage combine src/.coverage/
          ./venv/bin/python3 -m coverage xml
          mkdir -p coverage-report
          mv coverage.xml coverage-report/
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Upload coverage to codecov
        if: (success() || failure()) && steps.build.outcome == 'success'
        uses: codecov/codecov-action@v3
        with:
          directory: ./worktree-image/coverage-report
