name: Build documentation (PDF)

on:
  pull_request:
  push:
  workflow_dispatch:
    # Allow to run manually
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'ubuntu-focal-standard'
      docker_tag:
        description: 'Docker tag'
        required: true
        default: 'dev'

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge CI fixes from sagemath/sage
        run: |
          .ci/merge-fixes.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Start container
        run: |
          docker run --name BUILD -dit \
            --mount type=bind,src=$(pwd),dst=$(pwd) \
            --workdir $(pwd) \
            ghcr.io/sagemath/sage/sage-${{ github.event.inputs.platform || 'ubuntu-focal-standard' }}-with-targets:${{ github.event.inputs.docker_tag || 'dev'}} /bin/sh

      - name: Update system packages
        run: |
          export PATH="build/bin:$PATH"
          eval $(sage-print-system-package-command auto update)
          eval $(sage-print-system-package-command auto --yes --no-install-recommends install zip)
          eval $(sage-print-system-package-command auto --spkg --yes --no-install-recommends install git texlive)
        shell: sh .ci/docker-exec-script.sh BUILD . {0}

      - name: Add prebuilt tree as a worktree
        id: worktree
        run: |
          git config --global --add safe.directory $(pwd)
          git config --global user.email "ci-sage@example.com"
          git config --global user.name "Build & Test workflow"
          .ci/retrofit-worktree.sh worktree-image /sage
        shell: sh .ci/docker-exec-script.sh BUILD . {0}

      - name: Incremental build
        id: incremental
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          # Now re-bootstrap and build. The build is incremental because we were careful with the timestamps.
          ./bootstrap && make sagemath_doc_html-build-deps
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Build (fallback to non-incremental)
        id: build
        if: always() && steps.worktree.outcome == 'success' && steps.incremental.outcome != 'success'
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          make sagelib-clean && git clean -fx src/sage && ./config.status && make sagemath_doc_html-build-deps
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Build docs (PDF)
        id: docbuild
        if: always() && (steps.incremental.outcome == 'success' || steps.build.outcome == 'success')
        run: |
          export MAKE="make -j2 --output-sync=recurse" SAGE_NUM_THREADS=2
          make doc-clean doc-uninstall; make sagemath_doc_pdf-no-deps
        shell: sh .ci/docker-exec-script.sh BUILD ./worktree-image {0}

      - name: Copy docs
        id: copy
        if: always() && steps.docbuild.outcome == 'success'
        run: |
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          mkdir -p ./docs
          cp -r -L /sage/local/share/doc/sage/pdf ./docs
          # Zip everything for increased performance
          zip -r docs-pdf.zip docs
        shell: sh .ci/docker-exec-script.sh BUILD . {0}

      - name: Upload docs
        if: always() && steps.copy.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: docs-pdf
          path: docs-pdf.zip
